<?php

namespace AppBundle\Entity;

/**
 * ActualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualityRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderByDate()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('a')
		   ->from('AppBundle:Actuality', 'a')
		   ->orderBy('a.createdAt', 'DESC');

		return $qb->getQuery()
				  ->getResult();
	}

	public function findLatestActualityID()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('a')
		   ->from('AppBundle:Actuality', 'a')
		   ->orderBy('a.createdAt', 'DESC');

		return $qb->getQuery()
				  ->setMaxResults(1)
				  ->getResult();
	}

	public function findOneBySlug($params)
	{
	    if(is_array($params)){
	        $slug = $params['slug'];
	    }else{
	        $slug = $params;
	    }

	    $query = $this->createQueryBuilder('Actuality')
	                   ->where('Actuality.slug = :slug')
	                   ->setParameter('slug', $slug)
	                   ->getQuery();

	    $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

	    return $query->getOneOrNullResult();
	}
}
