<?php

namespace AppBundle\Entity;

/**
 * CommitteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllCommitteesByOrder()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('c')
		   ->from('AppBundle:Committee', 'c')
		   ->orderBy('c.order', 'ASC');

		return $qb->getQuery()
		          ->getResult();
	}
}
