<?php

namespace AppBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPagesNotNull()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('p')
		   ->from('AppBundle:Page', 'p')
		   ->where('p.seo IS NOT NULL');

		return $qb->getQuery()
		          ->getResult();
	}
}
