<?php

namespace AppBundle\Entity;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPaymentsByPlayerId($playerId)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('p')
		   ->from('AppBundle:Payment', 'p')
		   ->where('p.player = :playerId')
		   ->setParameter('playerId', $playerId);

		return $qb->getQuery()
		          ->getResult();
	}
}
