<?php

namespace AppBundle\Entity;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPlayersByTeamId($teamId)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('p')
		   ->from('AppBundle:Player', 'p')
		   ->where('p.team = :teamId')
		   ->setParameter('teamId', $teamId);

		return $qb->getQuery()
		          ->getResult();
	}

	public function findAllPlayersByName()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('p')
		   ->from('AppBundle:Player', 'p')
		   ->orderBy('p.name', 'ASC');

		return $qb->getQuery()
				  ->getResult();
	}
}
