<?php

namespace AppBundle\Entity;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllRegistrationsEnabled()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('r')
		   ->from('AppBundle:Registration', 'r')
		   ->where('r.enabled = :enabled')
		   ->setParameter('enabled', false);

		return $qb->getQuery()
		          ->getResult();
	}
}
