<?php

namespace AppBundle\Entity;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTeamsYoungByName()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('t')
		   ->from('AppBundle:Team', 't')
		   ->where('t.type = :type')
		   ->orderBy('t.name', 'ASC')
		   ->setParameter('type', 'young');

		return $qb->getQuery()
				  ->getResult();
	}

	public function findAllTeamsFirstByName()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('t')
		   ->from('AppBundle:Team', 't')
		   ->where('t.type = :type')
		   ->orderBy('t.name', 'ASC')
		   ->setParameter('type', 'first');

		return $qb->getQuery()
				  ->getResult();
	}

	public function findAllTeamsByName()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('t')
		   ->from('AppBundle:Team', 't')
		   ->orderBy('t.name', 'ASC');

		return $qb->getQuery()
				  ->getResult();
	}

	public function findOneBySlug($params)
	{
	    if(is_array($params)){
	        $slug = $params['slug'];
	    }else{
	        $slug = $params;
	    }

	    $query = $this->createQueryBuilder('Team')
	                   ->where('Team.slug = :slug')
	                   ->setParameter('slug', $slug)
	                   ->getQuery();

	    $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

	    return $query->getOneOrNullResult();
	}
}
