<?php

namespace AppBundle\Entity;

/**
 * TeamStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamStaffRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTeamStaffsByTeamId($teamId)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('s')
		   ->from('AppBundle:TeamStaff', 's')
		   ->where('s.team = :teamId')
		   ->setParameter('teamId', $teamId)
		   ->orderBy('s.order', 'ASC');

		return $qb->getQuery()
		          ->getResult();
	}
}
