<?php

namespace AppBundle\Entity;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends \Doctrine\ORM\EntityRepository
{
}
