<?php

namespace AppBundle\Entity;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTournamentRegistrationsByDateTournament($dateOfLatestTournament)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('tr')
		   ->from('AppBundle:TournamentRegistration', 'tr')
		   ->where('tr.date < :dateOfLatestTournament')
		   ->setParameter(':dateOfLatestTournament', $dateOfLatestTournament);

		return $qb->getQuery()
		          ->getResult();
	}
}
