<?php

namespace AppBundle\Entity;

/**
 * tournamentPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentPoolRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPoolsByTournamentId($tournamentId)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('s')
		   ->from('AppBundle:TournamentPool', 's')
		   ->where('s.tournament = :tournamentId')
		   ->setParameter('tournamentId', $tournamentId);

		return $qb->getQuery()
		          ->getResult();
	}
}
