<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findAllUsersByRole($role)
	{
	    $qb = $this->_em->createQueryBuilder();

	    $qb->select('u')
	       ->from('AppBundle:User', 'u')
	       ->where('u.roles LIKE :roles')
		   ->orderBy('u.username', 'ASC')
	       ->setParameter('roles', '%"' . $role . '"%');

	    return $qb->getQuery()->getResult();
	}
}
