security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login: 
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer : true
                remember_me: true
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            remember_me:
                key: %secret%
            anonymous: true

            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_user }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/utilisateurs, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/*, role: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
